version: '3.9'

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: exampledb
    volumes:
      - /tmp/shared_folder:/shared
    networks:
      - example_app

  web:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    image: talbarm/form-app:v1
    container_name: flask_web
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:secret@db:5432/exampledb
    volumes:
      - /tmp/shared_folder:/shared
    networks:
      - example_app

networks:
  example_app:
    driver: bridge
